
##
# RLStevenson Theme Options
####

# For baseurl:
# Use '' for / or '/your-dir' for another directory

title:		コメビュとかツールとか
description:	''
freetext:	''
baseurl:	''
version:	0.1.0
colorscheme:	'scheme-lightbrown'

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 url:		https://www.exchangerate-api.com
 name:		'ExchangeRate-API'

github:
 repo:		https://github.com/ryu-s/ryu-s.github.io


exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']