
##
# RLStevenson Theme Options
####

# For baseurl:
# Use '' for / or '/your-dir' for another directory

title:		コメビュとかツールとか
description:	''
freetext:	''
baseurl:	''
version:	0.1.0
colorscheme:	'scheme-lightbrown'

ga:		'UA-84804281-1'
piwikSiteID:	''
piwikURL:	''

author:
url: 'https://ryu-s.github.io'
name: 'ryu-s'

github:
repo:		https://github.com/ryu-s/ryu-s.github.io


exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem','sitemap.xml']
keep_files: ['BingSiteAuth.xml','sitemap.xml']
